<?php

namespace Pms\UserBundle\Permission\Provider;

/**
 * Security Provider
 *
 * @author Mohammad Emran Hasan <phpfour@gmail.com>
 */
class SecurityPermissionProvider implements ProviderInterface
{
    public function getPermissions()
    {
        return array(
            'ROLE_BUDGET_USERS'                       => array('ROLE_BUDGET_VIEW',
                                                               'ROLE_BUDGET_ADD'),
            'ROLE_BUDGET_APPROVE_USERS'               => array('ROLE_BUDGET_APPROVE_ONE',
                                                               'ROLE_BUDGET_APPROVE_TWO',
                                                               'ROLE_BUDGET_APPROVE_THREE'),
            'ROLE_RECEIVE_USERS'                      => array('ROLE_RECEIVE_VIEW',
                                                               'ROLE_RECEIVE_ADD'),
            'ROLE_REQUEST_PAYMENT_USERS'              => array('ROLE_REQUEST_FOR_PAYMENT',
                                                               'ROLE_REQUEST_FOR_PAYMENT_ADD'),
            'ROLE_ADVANCE_PAYMENT_USERS'              => array('ROLE_ADVANCE_PAYMENT_LOCAL',
                                                               'ROLE_ADVANCE_PAYMENT_HEAD',
                                                               'ROLE_ADVANCE_PAYMENT_ALL'),
            'ROLE_PAYMENT_APPROVE_USERS'              => array('ROLE_PAYMENT_APPROVE_ONE',
                                                               'ROLE_PAYMENT_APPROVE_TWO',
                                                               'ROLE_PAYMENT_APPROVE_THREE'),
            'ROLE_PURCHASE_REQUISITION_USERS'         => array('ROLE_PURCHASE_REQUISITION_CLOSE',
                                                               'ROLE_PURCHASE_REQUISITION_VIEW',
                                                               'ROLE_PURCHASE_REQUISITION_ADD'),
            'ROLE_PURCHASE_REQUISITION_APPROVE_USERS' => array('ROLE_PURCHASE_REQUISITION_APPROVE_ONE',
                                                               'ROLE_PURCHASE_REQUISITION_APPROVE_TWO',
                                                               'ROLE_PURCHASE_REQUISITION_APPROVE_THREE'),
            'ROLE_EDIT_USERS'                         => array('ROLE_PURCHASE_REQUISITION_EDIT',
                                                               'ROLE_PURCHASE_ORDER_EDIT',
                                                               'ROLE_BUDGET_EDIT',
                                                               'ROLE_BANK_TRANSACTION_EDIT',
                                                               'ROLE_BANK_EDIT',
                                                               'ROLE_INVENTORY_DELIVERY_EDIT',
                                                               'ROLE_INVENTORY_STOCK_EDIT',
                                                               'ROLE_DOCUMENT_EDIT',
                                                               'ROLE_RECEIVE_EDIT'),
            'ROLE_PURCHASE_REQUISITION_CLAIM_USERS'   => array('ROLE_PURCHASE_REQUISITION_CLAIM'),
            'ROLE_PURCHASE_ORDER_AMENDMENT_USERS'     => array('ROLE_PURCHASE_ORDER_AMENDMENT'),
            'ROLE_COMMENTS_USERS'                     => array('ROLE_COMMENTS_USERS'),
            'ROLE_BUYER_USERS'                        => array('ROLE_BUYER_USERS'),
            'ROLE_ACCOUNT_HEAD_OFFICE_USERS'          => array('ROLE_ACCOUNT_HEAD_OFFICE'),
            'ROLE_ACCOUNT_LOCAL_OFFICE_USERS'         => array('ROLE_ACCOUNT_LOCAL_OFFICE'),
            'ROLE_PURCHASE_ORDER_USERS'               => array('ROLE_PURCHASE_ORDER_VIEW',
                                                               'ROLE_PURCHASE_ORDER_ADD'),
            'ROLE_PURCHASE_ORDER_APPROVE_USERS'       => array('ROLE_PURCHASE_ORDER_APPROVE_ONE',
                                                               'ROLE_PURCHASE_ORDER_APPROVE_TWO',
                                                               'ROLE_PURCHASE_ORDER_APPROVE_THREE'),
            'ROLE_DOCUMENT_USERS'                     => array('ROLE_DOCUMENT_VIEW', 'ROLE_DOCUMENT_ADD'),
            'ROLE_REPORT_USERS'                       => array('ROLE_REPORT_VIEW'),
            'ROLE_MANAGER_REPORT'                     => array('ROLE_MANAGER_REPORT_VIEW'),
            'ROLE_BANK_USERS'                         => array('ROLE_BANK_VIEW',
                                                              'ROLE_BANK_ADD',
                                                              'ROLE_BANK_DELETE'),
            'ROLE_BANK_TRANSACTION'                   => array('ROLE_BANK_TRANSACTION_VIEW',
                                                              'ROLE_BANK_TRANSACTION_ADD',
                                                              'ROLE_BANK_TRANSACTION_DELETE'),
            'ROLE_BANK_REPORT'                        => array('ROLE_BANK_REPORT_VIEW'),
            'ROLE_INVENTORY'                          => array('ROLE_INVENTORY_DELIVERY_VIEW',
                                                              'ROLE_INVENTORY_DELIVERY_ADD',
                                                              'ROLE_INVENTORY_DELIVERY_DELETE'),
            'ROLE_INVENTORY_STOCK'                    => array('ROLE_INVENTORY_STOCK_VIEW',
                                                              'ROLE_INVENTORY_STOCK_ADD',
                                                              'ROLE_INVENTORY_STOCK_DELETE'),
            'ROLE_INVENTORY_REPORT'                   => array('ROLE_INVENTORY_STOCK_REPORT_VIEW'),
            'ROLE_AREA_USERS'                         => array('ROLE_AREA_VIEW',
                                                               'ROLE_AREA_ADD',
                                                               'ROLE_AREA_UPDATE',
                                                               'ROLE_AREA_DELETE',
                                                               'ROLE_AREA_RESTORE'),
            'ROLE_CATEGORY_USERS'                     => array('ROLE_CATEGORY_VIEW',
                                                               'ROLE_CATEGORY_ADD',
                                                               'ROLE_CATEGORY_UPDATE',
                                                               'ROLE_CATEGORY_DELETE',
                                                               'ROLE_CATEGORY_RESTORE'),
            'ROLE_COST_HEADER_USERS'                  => array('ROLE_COST_HEADER_VIEW',
                                                               'ROLE_COST_HEADER_ADD',
                                                               'ROLE_COST_HEADER_UPDATE',
                                                               'ROLE_COST_HEADER_DELETE',
                                                               'ROLE_COST_HEADER_RESTORE'),
            'ROLE_ITEM_USERS'                         => array('ROLE_ITEM_VIEW',
                                                               'ROLE_ITEM_ADD',
                                                               'ROLE_ITEM_UPDATE',
                                                               'ROLE_ITEM_DELETE',
                                                               'ROLE_ITEM_RESTORE'),
            'ROLE_ITEM_TYPE_USERS'                    => array('ROLE_ITEM_TYPE_VIEW',
                                                               'ROLE_ITEM_TYPE_ADD',
                                                               'ROLE_ITEM_TYPE_UPDATE',
                                                               'ROLE_ITEM_TYPE_DELETE',
                                                               'ROLE_ITEM_TYPE_RESTORE'),
            'ROLE_PROJECT_USERS'                      => array('ROLE_PROJECT_VIEW',
                                                               'ROLE_PROJECT_ADD',
                                                               'ROLE_PROJECT_UPDATE',
                                                               'ROLE_PROJECT_DELETE',
                                                               'ROLE_PROJECT_RESTORE'),
            'ROLE_PROJECT_TYPE_USERS'                 => array('ROLE_PROJECT_TYPE_VIEW',
                                                               'ROLE_PROJECT_TYPE_ADD',
                                                               'ROLE_PROJECT_TYPE_UPDATE',
                                                               'ROLE_PROJECT_TYPE_DELETE',
                                                               'ROLE_PROJECT_TYPE_RESTORE'),
            'ROLE_SUB_CATEGORY_USERS'                 => array('ROLE_SUB_CATEGORY_VIEW',
                                                               'ROLE_SUB_CATEGORY_ADD',
                                                               'ROLE_SUB_CATEGORY_UPDATE',
                                                               'ROLE_SUB_CATEGORY_DELETE',
                                                               'ROLE_SUB_CATEGORY_RESTORE'),
            'ROLE_TERMS_AND_CONDITIONS_USERS'         => array('ROLE_TERMS_AND_CONDITIONS_VIEW',
                                                               'ROLE_TERMS_AND_CONDITIONS_ADD',
                                                               'ROLE_TERMS_AND_CONDITIONS_UPDATE',
                                                               'ROLE_TERMS_AND_CONDITIONS_DELETE',
                                                               'ROLE_TERMS_AND_CONDITIONS_RESTORE'),
            'ROLE_VENDOR_USERS'                       => array('ROLE_VENDOR_VIEW',
                                                               'ROLE_VENDOR_ADD',
                                                               'ROLE_VENDOR_UPDATE',
                                                               'ROLE_VENDOR_DELETE',
                                                               'ROLE_VENDOR_RESTORE'),
            'ROLE_PURCHASE_TYPE_USERS'                => array('ROLE_PURCHASE_TYPE_VIEW',
                                                               'ROLE_PURCHASE_TYPE_ADD',
                                                               'ROLE_PURCHASE_TYPE_UPDATE',
                                                               'ROLE_PURCHASE_TYPE_DELETE',
                                                               'ROLE_PURCHASE_TYPE_RESTORE'),
            'ROLE_COMPANY_SETTING_USERS'              => array('ROLE_COMPANY_SETTING_VIEW',
                                                               'ROLE_COMPANY_SETTING_ADD',
                                                               'ROLE_COMPANY_SETTING_UPDATE',
                                                               'ROLE_COMPANY_SETTING_DELETE',
                                                               'ROLE_COMPANY_SETTING_RESTORE'),
            'ROLE_RELATED_BANK_USERS'                 => array('ROLE_RELATED_BANK_VIEW',
                                                               'ROLE_RELATED_BANK_ADD'),
            'ROLE_HISTORY_USERS'                      => array('ROLE_PO_HISTORY_USERS',
                                                               'ROLE_PR_HISTORY_USERS',
                                                               'ROLE_R_HISTORY_USERS',
                                                               'ROLE_B_HISTORY_USERS'),
            'ROLE_PROCUREMENT_USERS'                  => array('ROLE_PROCUREMENT_LOCAL',
                                                               'ROLE_PROCUREMENT_HEAD',
                                                               'ROLE_PROCUREMENT_ALL'),
            'ROLE_ACCOUNT_USERS'                      => array('ROLE_ACCOUNT_LOCAL',
                                                               'ROLE_ACCOUNT_HEAD',
                                                               'ROLE_ACCOUNT_ALL'),
            'ROLE_DASHBOARD'                          => array( 'ROLE_DASHBOARD_VIEW'),
            'ROLE_PAYMENT_USERS'                      => array('ROLE_PAYMENT_VIEW'),
            'ROLE_MGT_REPORT_USERS'                   => array('ROLE_MGT_REPORT_VIEW'),
            'ROLE_ACCOUNT_ENTRY_USERS'                => array('ROLE_ACCOUNT_ENTRY_LOCAL',
                                                               'ROLE_ACCOUNT_ENTRY_HEAD',
                                                               'ROLE_ACCOUNT_ENTRY_ALL'),
            'ROLE_SUPER_ADMIN'                        => array('ROLE_BUDGET_APPROVE_USERS',
                                                               'ROLE_BUDGET_USERS',
                                                               'ROLE_PURCHASE_REQUISITION_USERS',
                                                               'ROLE_REPORT_USERS',
                                                               'ROLE_RELATED_BANK_USERS',
                                                               'ROLE_SUPER_ADMIN',
                                                               'ROLE_HISTORY_USERS'),

            'ROLE_PR_ITEM_CLOSE'                      => array('ROLE_PR_ITEM_CLOSE_HEAD_OFFICE',
                                                               'ROLE_PR_ITEM_CLOSE_LOCAL_OFFICE'),

            'ROLE_RECEIVE_ITEM_CLOSE'                 => array('ROLE_RECEIVE_ITEM_CLOSE_HEAD_OFFICE',
                                                               'ROLE_RECEIVE_ITEM_CLOSE_LOCAL_OFFICE'),

            'ROLE_INVENTORY_PROJECT_TO_PROJECT'        => array('ROLE_PROJECT_TO_PROJECT_DELIVERY')
        );
    }
}