<?php

namespace Pms\SettingBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectTypeRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }

    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }

    public function update($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $this->_em;
    }

    public function getAllAsArray()
    {
        $data = array();

        foreach ($this->findAll() as $row) {
            $data[$row->getId()] = $row->getName();
        }

        return $data;
    }

    public function getProjectTypeSearch($status, $returnQuery = true)
    {
        $query = $this->createQueryBuilder('pt');
        $query->orderBy('pt.projectCategoryName', 'asc');

        $this->handleActiveTypeFilter($status, $query);

        $this->handleDeleteTypeFilter($status, $query);

        if ($returnQuery) {
            return $query;
        }

        return $query->getQuery()->getResult();
    }

    /**
     * @param $status
     * @param $query
     */
    protected function handleActiveTypeFilter($status, $query)
    {
        if ($status == 'active') {
            $query->andWhere('pt.status = :status');
            $query->setParameter('status', 1);
        }
    }

    /**
     * @param $status
     * @param $query
     */
    protected function handleDeleteTypeFilter($status, $query)
    {
        if ($status == 'delete') {
            $query->andWhere('pt.status = :status');
            $query->setParameter('status', 0);
        }
    }
}
