<?php

namespace Pms\SettingBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PurchaseTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseTypeRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }

    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }

    public function update($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $this->_em;
    }

    public function getPurchaseTypeSearch($status, $returnQuery = true)
    {
        $query = $this->createQueryBuilder('pt');
        $query->orderBy('pt.name', 'asc');

        $this->handleActiveTypeFilter($status, $query);

        $this->handleDeleteTypeFilter($status, $query);

        if ($returnQuery) {
            return $query;
        }

        return $query->getQuery()->getResult();
    }

    /**
     * @param $status
     * @param $query
     */
    protected function handleActiveTypeFilter($status, $query)
    {
        if ($status == 'active') {
            $query->andWhere('pt.status = :status');
            $query->setParameter('status', 1);
        }
    }

    /**
     * @param $status
     * @param $query
     */
    protected function handleDeleteTypeFilter($status, $query)
    {
        if ($status == 'delete') {
            $query->andWhere('pt.status = :status');
            $query->setParameter('status', 0);
        }
    }

    public function findAllPurchaseType()
    {

        $query = $this->createQueryBuilder('pt');
/*        $query->leftJoin('pt.purchaseOrder','po');
        $query->leftJoin('po.purchaseOrderItems','poi');
        $query->leftJoin('poi.project','p');*/
        $query->select('pt.id');
        $query->addSelect('pt.name');
        $query->orderBy('pt.id', 'DESC');

        return $query->getQuery()->getResult();
    }
}
