<?php

namespace Pms\SettingBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCategoryRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }

    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }

    public function update($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $this->_em;
    }

    public function getSubCategories($category)
    {
        $query = $this->createQueryBuilder('sc');
        $query->select('sc.id');
        $query->addSelect('sc.subCategoryName');
        $query->where('sc.category = :category');
        $query->andWhere('sc.status = 1');
        $query->setParameter('category', $category);

        return $query->getQuery()->getResult();
    }

    public function getSubCategorySearch($status, $returnQuery = true)
    {
        $query = $this->createQueryBuilder('sc');
        $query->orderBy('sc.subCategoryName', 'asc');

        $this->handleActiveTypeFilter($status, $query);

        $this->handleDeleteTypeFilter($status, $query);

        if ($returnQuery) {
            return $query;
        }

        return $query->getQuery()->getResult();
    }

    /**
     * @param $status
     * @param $query
     */
    protected function handleActiveTypeFilter($status, $query)
    {
        if ($status == 'active') {
            $query->andWhere('sc.status = :status');
            $query->setParameter('status', 1);
        }
    }

    /**
     * @param $status
     * @param $query
     */
    protected function handleDeleteTypeFilter($status, $query)
    {
        if ($status == 'delete') {
            $query->andWhere('sc.status = :status');
            $query->setParameter('status', 0);
        }
    }

    public function findAllSubCategory()
    {
        $query = $this->createQueryBuilder('sc');
        $query->select('sc.id');
        $query->addSelect('sc.subCategoryName');
        $query->orderBy('sc.subCategoryName', 'ASC');

        return $query->getQuery()->getResult();
    }
}
