homepage:
    pattern: /
    defaults: { _controller: UserBundle:Default:index }
    options:  { mobile: redirect, tablet: no_redirect, full: redirect_without_path }

user_search:
    pattern: /users/search/
    defaults: { _controller: UserBundle:User:search }

user_excel_excelUsersList:
    pattern: /users/excelUsersList
    defaults: { _controller: UserBundle:User:excelUsersList }
    requirements:
          id:  \d+

user_deactive:
    pattern: /user/deactive/{id}
    defaults: { _controller: UserBundle:User:userDeactive }
    requirements:
          id: \d+

user_password_edit:
    pattern: /user/password/edit/{id}
    defaults: { _controller: UserBundle:ManageUser:userPasswordEdit }
    requirements:
          id: \d+

password_edit:
    pattern: /password/edit/{id}
    defaults: { _controller: UserBundle:User:passwordEdit }
    requirements:
          id: \d+

user_active:
    pattern: /user/active/{id}
    defaults: { _controller: UserBundle:User:userActive }
    requirements:
          id: \d+

username_check:
    pattern: /username/check
    defaults: { _controller: UserBundle:User:usernameCheck }
    options:
            expose: true

email_check:
    pattern: /email/check
    defaults: { _controller: UserBundle:User:emailCheck }
    options:
            expose: true

fos_user_security:
     resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
     resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
     prefix: /profile

fos_user_register:
     resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
     prefix: /register

fos_user_resetting:
     resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
     prefix: /resetting

fos_user_change_password:
     resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
     prefix: /profile

pms_user_group:
    resource: "@UserBundle/Resources/config/user/user-manage.yml"
    prefix: /users
