area_refresh:
    pattern: /area/refresh
    defaults: { _controller: PmsSettingBundle:Area:refresh }

area_active:
    pattern: /area/active/{id}
    defaults: { _controller: PmsSettingBundle:Area:active }
    requirements:
          id: \d+

area_delete:
    pattern: /area/delete/{id}
    defaults: { _controller: PmsSettingBundle:Area:delete }
    requirements:
          id: \d+

area_update:
    pattern: /area/update/{id}
    defaults: { _controller: PmsSettingBundle:Area:update }
    requirements:
          id:  \d+

area_check:
    pattern: /area/check
    defaults: { _controller: PmsSettingBundle:Area:check }
    options:
            expose: true

area_ajax_add:
    pattern: /area/add
    defaults: { _controller: PmsSettingBundle:Area:add }
    options:
            expose: true

area:
    pattern: /area/{status}
    defaults: { _controller: PmsSettingBundle:Area:index, status:active }