parameters:
#    pms_petty_cash.example.class: Pms\PettyCashBundle\Example

services:
#    pms_petty_cash.example:
#        class: %pms_petty_cash.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
