report_purchase_order:
    pattern: /purchase-order-report
    defaults: { _controller: PmsReportBundle:PurchaseOrderReport:purchaseOrderReport }

report_purchase_order_excel:
    pattern: /purchase-order-report-excel
    defaults: { _controller: PmsReportBundle:PurchaseOrderReport:purchaseOrderReportExcel }
    options:
           expose: true